### ISSUE TITLE
Hoping to discuss the cow lab with you 

### ISSUE THREAD

**Issue by Jugg-zh** [wordless-dot/xv6-labs-2021#1]
Hi there, I'm failing on the createdelete part of the usertests, can we discuss about this lab together?

**Comment by wordless-dot** [comment]
Hi!
I'm sorry that the email server marked the emails from GitHub as SPAM, so I did not see your issue until now.
I think you could publicize your repository so that I can see your code. I'm glad to discuss the lab with you.

**Comment by Jugg-zh** [comment]
Congrats on passing all the tests!
